import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually defined sidebar to control the order of the modules
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Robotic Nervous System',
      items: [{type: 'autogenerated', dirName: '01-robotic-nervous-system'}],
    },
    {
      type: 'category',
      label: 'Digital Twin',
      items: [{type: 'autogenerated', dirName: '02-digital-twin'}],
    },
    {
      type: 'category',
      label: 'AI Robot Brain',
      items: [{type: 'autogenerated', dirName: '03-ai-robot-brain'}],
    },
    {
      type: 'category',
      label: 'VLA Models',
      items: [{type: 'autogenerated', dirName: '04-vla'}],
    },
  ],
};

export default sidebars;
